spring:
  output:
    ansi:
      enabled: ALWAYS
  devtools:
    livereload:
      enabled: false
  servlet:
    encoding:
      charset: UTF-8
      force: true
  aop:
    proxy-target-class: true
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

ably_auth:
  auth_system:
    secret-key: ABLY_SECRET_KEY
    issuer: ABLY-AUTH-SYSTEM