spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:ably;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
  output:
    ansi:
      enabled: always
  config:
    activate:
      on-profile: local

# server
server:
  port: 8080
  servlet:
    context-path: /

application:
  environment: local

## logging
logging:
  level:
    com.ably.project: debug
    org.springframework: info

sentry:
  enabled: true
  environment: local

# feign client
feign:
  autoconfiguration:
    jackson:
      enabled: true
  ably-api:
    url: http://localhost:8080
  httpclient:
    connection-timeout: 1000
  client:
    config:
      log-client:
        loggerLevel: FULL
